"""SQLAlchemy declarative base and shared model building blocks.

Kept separate from `session.py` so that model modules (e.g.
`modules/identity/domain/models.py`, added in a later task) can import
`Base`/`TimestampMixin` without pulling in the async engine or any
runtime settings dependency.
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import MetaData, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# A fixed naming convention makes Alembic's autogenerated constraint/index
# names deterministic and diffable across migrations, instead of the
# database driver choosing an unpredictable name per environment.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base shared by every ORM model in the application.

    Domain/application code (Architecture.md §4) never imports this
    directly for business logic — only the persistence adapter layer of
    each module does, keeping domain entities free of SQLAlchemy.
    """

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class TimestampMixin:
    """Adds `created_at`/`updated_at` to a mutable entity (Database.md §2).

    Append-only/event tables use their own `occurred_at` column instead of
    this mixin — they are not mutable rows with an update lifecycle.
    """

    created_at: Mapped[datetime] = mapped_column(
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
